name: Build with CMake

on:
  workflow_dispatch:

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
 
      - name: Configure with CMake
        run: cmake -B build -S ${{ github.workspace }}

      - name: Build with CMake
        run: cmake --build build

      - name: Hola, amigos
        run: ${{ github.workspace }}/build/hola